version: '3'

services:
  jenkins:
    container_name: jenkins
    image: jenkins/jenkins:lts-jdk11
    restart: always
    ports:
      - 9000:8080
      - 50000:50000
    volumes:
      - jenkins_home:/var/jenkins_home
    networks:
      - jenkins_network

networks:
  jenkins_network:
    driver: bridge
    name: jenkins_network

volumes:
  jenkins_home:
    driver: local
    name: jenkins_home